services:
  # -- Database -- #
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data  
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # -- Redis -- #
  redis:
    image: redis:8.6
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 30s
      retries: 5
    mem_limit: 256m
    cpus: 0.3

  # -- Flask API -- #
  threat-service:
    build: ./product
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
    volumes:
      - ./product:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    mem_limit: 512m
    cpus: 0.5

  # -- Frontend -- #
  web:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    environment:
      FLASK_HOST: ${FLASK_HOST}
      FLASK_PORT: ${FLASK_PORT}
    expose:
      - "80"
    depends_on:
      - threat-service
    networks:
      - app-network
  
  # -- Nginx --#
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
      - threat-service
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s
    mem_limit: 128m
    cpus: 0.2

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - app-network

  #-- Grafana --#
  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=http://my.grafana.server/
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - app-network

  #-- InfluxDB --#
  influxdb2:
    image: influxdb:2.8
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: docs
      DOCKER_INFLUXDB_INIT_BUCKET: home    
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
      - ./secrets/influxdb2-admin-username:/run/secrets/influxdb2-admin-username:ro
      - ./secrets/influxdb2-admin-password:/run/secrets/influxdb2-admin-password:ro
      - ./secrets/influxdb2-admin-token:/run/secrets/influxdb2-admin-token:ro
    networks:
      - app-network

volumes:
  pgdata:
  grafana-data:
  influxdb2-data:
  influxdb2-config:

networks:
  app-network:
    driver: bridge
